# The schedule is read from top to bottom, which means that the first defined traffic class will be active first
#
# Available traffic classes are:
# isochronous
# cyclic-sync
# cyclic-async
# alarms-events
# config-diag
# network-control
# best-effort

gating-cycle: 5 # ms
traffic-classes:
  - name: isochronous
    assigned-portion: 20 # percent
  - name: cyclic-async
    assigned-portion: 15 # percent